---
title: ""
runtime: shiny
output: html_document
---

```{r, echo=F, warning=F, message=F, results='hide', error=FALSE}
library(fields)
library(reshape2)

random.colors <- function(row.n, col.n, n)
{
  
  random.r <- sample(0:255, n, replace=T)/255
  random.g <- sample(0:255, n, replace=T)/255
  random.b <- sample(0:255, n, replace=T)/255
  random.row <- sample(1:row.n, n, replace=T)
  random.col <- sample(1:col.n, n, replace=T)
  
  dedup <- !duplicated(paste(random.row,random.col,sep=" - "))
  
  starting.colors <- data.frame(row=random.row, col=random.col, red=random.r, green=random.g, blue=random.b) 
  starting.colors <- starting.colors[dedup,]
  starting.colors$color <- rgb(red=starting.colors$red, green=starting.colors$green, blue=starting.colors$blue)
  
  return(starting.colors)
}

random.picture <- function(row.n=10, col.n=10, starting.colors, exponent=1, interpolate=F, highlight=F)
{
  
  starting.matrix <- data.frame(row=rep(1:row.n, times=col.n), col=sort(rep(1:col.n, times=row.n)))
  starting.matrix <- merge(starting.matrix, starting.colors[,c("row","col","color")], by=c("row","col"), all.x=T, all.y=F)
  starting.matrix <- acast(starting.matrix, row~col, value.var="color")
  
  image <- data.frame(row=rep(1:row.n, times=col.n), col=sort(rep(1:col.n, times=row.n)))
  image <- image[!paste(image$row,image$col,sep="-")%in%paste(starting.colors$row,starting.colors$col,sep="-"),]
  

  dist.matrix <- as.matrix(rdist(image[,c("col","row")],starting.colors[,c("col","row")]))
  dist.matrix <- 1/(dist.matrix^exponent)
  dist.matrix <- (dist.matrix)/rowSums(dist.matrix)
#   dist.matrix <- (dist.matrix)/apply(dist.matrix,1,sum)

  
  image$red.new <- (dist.matrix %*% starting.colors$red)
  image$green.new <- (dist.matrix %*% starting.colors$green)
  image$blue.new <- (dist.matrix %*% starting.colors$blue)
  
  image$color <- rgb(red=image$red.new, green=image$green.new, blue=image$blue.new, alpha=1, maxColorValue=1)
  image.matrix <- acast(image, row~col, value.var="color", interpolate=F)
  
  par(mar=c(0,0,0,0))
  plot(0,0,type="n",xlim=c(0,col.n),ylim=c(0,row.n), xlab="", ylab="", xaxt="n", yaxt="n", frame=F, xaxs="i", yaxs="i")
  rasterImage(image.matrix, xleft=0, ybottom=row.n, xright=col.n, ytop=0, interpolate=interpolate)
  rasterImage(starting.matrix, xleft=0, ybottom=row.n, xright=col.n, ytop=0, interpolate=F)
  
  if(highlight==T)
  {
    starting.colors$border <- ifelse((0.299*starting.colors$red + 0.587*starting.colors$green + 0.114*starting.colors$blue)>0.5,"#000000","#FFFFFF")
    rect(starting.colors$col-1, starting.colors$row-1, starting.colors$col, starting.colors$row, col=NA, border=starting.colors$border)
  }
}
```


```{r, echo=FALSE}
  
par(mfrow=c(1,1))
download.res <- rbind(c(1920,1080),c(1366,1024),c(1280,1024))

picture <- reactive({
  random.colors(as.numeric(input$resolution), as.numeric(input$resolution)*(3), input$starting.colors)
})

renderPlot({
  random.picture(row.n=as.numeric(input$resolution), 
                 col.n=as.numeric(input$resolution)*(3), 
                 starting.colors=picture(), 
                 exponent=input$exponent, 
                 interpolate=F, 
                 highlight=input$highlight)
}, height = 240, width = 700)

inputPanel(
  
  sliderInput("starting.colors", label = "Number of starting colors:",
              min=1, max=20, value=3, step=1, width=200),
  
  sliderInput("exponent", label = "Distance matrix exponent:",
              min=-20, max=20, value=1, step=1, 
              animate=animationOptions(interval = 100, loop = FALSE, playButton = NULL, pauseButton = NULL), width=200),
  
  radioButtons("resolution", "Resolution:", choices=c("8 x 24" = 8, "16 x 48" = 16, "32 x 96" = 32), selected=8),
  
  checkboxInput("highlight", label="Highlight",
                value=F)
  )

inputPanel(
  radioButtons("download.res", "Download Size:", choices=c("1920 x 1080" = 1, "1366 x 768" = 2, "1280 x 1024" = 3), selected=1),
  downloadButton('downloadPlot', 'Download Plot')
  )

output$downloadPlot <- downloadHandler(
    filename = function() { paste("Image.",format(Sys.time(), "%H.%M.%S"),'.png', sep='') },
    content = function(file) {
      row.res <- round(download.res[as.numeric(input$download.res),2]*as.numeric(input$resolution)/500)
      col.res <- round(download.res[as.numeric(input$download.res),1]*as.numeric(input$resolution)/500)
      image <- picture()
      image$row <- round( (image$row/as.numeric(input$resolution)) * row.res )
      image$col <- round( (image$col/(as.numeric(input$resolution)*3)) * col.res)
      png(file, width=download.res[as.numeric(input$download.res),1], height=download.res[as.numeric(input$download.res),2])
      random.picture(row.n=row.res, 
                     col.n=col.res, 
                     starting.colors=image, 
                     exponent=input$exponent, 
                     interpolate=F, 
                     highlight=input$highlight)
      dev.off()
    },
    contentType="image/png")
```



